### ISSUE TITLE
context takrorlanishi

### ISSUE THREAD

**Issue by IsmoilAzamov** [ahadjonovss/localization_pro#1]
Doim context berish shartmi? 
main functionni ichida intialize method ochib global context qoshishni bir qarab koring.

Doim context tashib yurish yurakka sig`maydida

**Comment by ahadjonovss** [comment]
Assalomu alaykum, muammo 1.0.2 versiyamizda bartaraf etildi!

**Comment by ahadjonovss** [comment]
Assalomu alaykum, muammo 1.0.2 versiyamizda bartaraf etildi!
